databases:
  - name: Esmark
    databaseName: Esmark
    user: Esmark

services:
  - type: web
    name: Esmark
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Esmark
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
