services:
  - type: web
    name: Esmark
    runtime: ruby
    buildCommand: "bundle install"  # Customize this as needed
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Esmark
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
